name: Test and Coverage
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests
        run: npx jest --coverage --runInBand --silent
        env:
          PORT: 3000
          DB: soporteremoto-tier
          LNET6_BOT_URL: http://localhost:3000/send-key
          NODE_ENV: test

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
