name: Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/jest-action@1.0.0
        env:
          PORT: 3000
          DB: soporteremoto-tier
          LNET6_BOT_URL: http://localhost:3000/send-key
          NODE_ENV: test
        with:
          args:  --coverage --runInBand --silent
